# Generated by Django 5.1.2 on 2024-10-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaVerde', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='static/tiendaVerde/imagenes/'),
        ),
    ]
